// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package mpl_token_metadata

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetAndVerifyCollection is the `SetAndVerifyCollection` instruction.
type SetAndVerifyCollection struct {

	// [0] = [WRITE] metadata
	//
	// [1] = [SIGNER] collectionAuthority
	//
	// [2] = [SIGNER] payer
	//
	// [3] = [] updateAuthority
	//
	// [4] = [] collectionMint
	//
	// [5] = [] collection
	//
	// [6] = [] collectionMasterEditionAccount
	//
	// [7] = [] collectionAuthorityRecord
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetAndVerifyCollectionInstructionBuilder creates a new `SetAndVerifyCollection` instruction builder.
func NewSetAndVerifyCollectionInstructionBuilder() *SetAndVerifyCollection {
	nd := &SetAndVerifyCollection{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	return nd
}

// SetMetadataAccount sets the "metadata" account.
func (inst *SetAndVerifyCollection) SetMetadataAccount(metadata ag_solanago.PublicKey) *SetAndVerifyCollection {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(metadata).WRITE()
	return inst
}

// GetMetadataAccount gets the "metadata" account.
func (inst *SetAndVerifyCollection) GetMetadataAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetCollectionAuthorityAccount sets the "collectionAuthority" account.
func (inst *SetAndVerifyCollection) SetCollectionAuthorityAccount(collectionAuthority ag_solanago.PublicKey) *SetAndVerifyCollection {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(collectionAuthority).SIGNER()
	return inst
}

// GetCollectionAuthorityAccount gets the "collectionAuthority" account.
func (inst *SetAndVerifyCollection) GetCollectionAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetPayerAccount sets the "payer" account.
func (inst *SetAndVerifyCollection) SetPayerAccount(payer ag_solanago.PublicKey) *SetAndVerifyCollection {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(payer).SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *SetAndVerifyCollection) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetUpdateAuthorityAccount sets the "updateAuthority" account.
func (inst *SetAndVerifyCollection) SetUpdateAuthorityAccount(updateAuthority ag_solanago.PublicKey) *SetAndVerifyCollection {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(updateAuthority)
	return inst
}

// GetUpdateAuthorityAccount gets the "updateAuthority" account.
func (inst *SetAndVerifyCollection) GetUpdateAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetCollectionMintAccount sets the "collectionMint" account.
func (inst *SetAndVerifyCollection) SetCollectionMintAccount(collectionMint ag_solanago.PublicKey) *SetAndVerifyCollection {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(collectionMint)
	return inst
}

// GetCollectionMintAccount gets the "collectionMint" account.
func (inst *SetAndVerifyCollection) GetCollectionMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetCollectionAccount sets the "collection" account.
func (inst *SetAndVerifyCollection) SetCollectionAccount(collection ag_solanago.PublicKey) *SetAndVerifyCollection {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(collection)
	return inst
}

// GetCollectionAccount gets the "collection" account.
func (inst *SetAndVerifyCollection) GetCollectionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetCollectionMasterEditionAccountAccount sets the "collectionMasterEditionAccount" account.
func (inst *SetAndVerifyCollection) SetCollectionMasterEditionAccountAccount(collectionMasterEditionAccount ag_solanago.PublicKey) *SetAndVerifyCollection {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(collectionMasterEditionAccount)
	return inst
}

// GetCollectionMasterEditionAccountAccount gets the "collectionMasterEditionAccount" account.
func (inst *SetAndVerifyCollection) GetCollectionMasterEditionAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetCollectionAuthorityRecordAccount sets the "collectionAuthorityRecord" account.
func (inst *SetAndVerifyCollection) SetCollectionAuthorityRecordAccount(collectionAuthorityRecord ag_solanago.PublicKey) *SetAndVerifyCollection {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(collectionAuthorityRecord)
	return inst
}

// GetCollectionAuthorityRecordAccount gets the "collectionAuthorityRecord" account.
func (inst *SetAndVerifyCollection) GetCollectionAuthorityRecordAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst SetAndVerifyCollection) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetAndVerifyCollection,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetAndVerifyCollection) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetAndVerifyCollection) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Metadata is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.CollectionAuthority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.UpdateAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.CollectionMint is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Collection is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.CollectionMasterEditionAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.CollectionAuthorityRecord is not set")
		}
	}
	return nil
}

func (inst *SetAndVerifyCollection) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetAndVerifyCollection")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                 metadata", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("      collectionAuthority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                    payer", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("          updateAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("           collectionMint", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("               collection", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("  collectionMasterEdition", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("collectionAuthorityRecord", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj SetAndVerifyCollection) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *SetAndVerifyCollection) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewSetAndVerifyCollectionInstruction declares a new SetAndVerifyCollection instruction with the provided parameters and accounts.
func NewSetAndVerifyCollectionInstruction(
	// Accounts:
	metadata ag_solanago.PublicKey,
	collectionAuthority ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	updateAuthority ag_solanago.PublicKey,
	collectionMint ag_solanago.PublicKey,
	collection ag_solanago.PublicKey,
	collectionMasterEditionAccount ag_solanago.PublicKey,
	collectionAuthorityRecord ag_solanago.PublicKey) *SetAndVerifyCollection {
	return NewSetAndVerifyCollectionInstructionBuilder().
		SetMetadataAccount(metadata).
		SetCollectionAuthorityAccount(collectionAuthority).
		SetPayerAccount(payer).
		SetUpdateAuthorityAccount(updateAuthority).
		SetCollectionMintAccount(collectionMint).
		SetCollectionAccount(collection).
		SetCollectionMasterEditionAccountAccount(collectionMasterEditionAccount).
		SetCollectionAuthorityRecordAccount(collectionAuthorityRecord)
}
